### ISSUE TITLE
what distro do you use?

### ISSUE THREAD

**Issue by elvisisvan** [AkshatBaranwal/dotfiles#5]
im running fedora 37 so is there something i should know before applying these configurations? (don't want to unintentionally break the system :)

**Comment by AkshatBaranwal** [comment]
I use Manjaro, and have no experience with Fedora.
The script in README will create a backup of the original before replacing it.
In case you're not sure whether to apply them, you may manually apply the configurations.

To setup:
Install zsh
Copy .bash_function, .zshrc and .vimrc into your home folder
Install the plugins mentioned in .zshrc and .vimrc
done!

To additionally setup trackpad gestures:
Enable X11
Install libinput-gestures
Copy the libinput-gestures.conf to ~/.config

The rest of the configurations I made were specifically for my hardware, and you may not find them useful.
